- hosts: single
  remote_user: faurik
  become: yes
  tasks:
    - name: Run app instances
      include_role: 
        name: faurik.ansible_install_exam_app
      vars:
        container_name: "{{ item }}"
      with_items: "{{ app_containers }}"
    - name: Run nginx
      include_role: 
        name: faurik.ansible_nginx_balancer
