- hosts: single
  remote_user: faurik
  become: yes
  tasks:
    - name: Run app instances
      include_role: 
        name: setup-app
      vars:
        container_name: "{{ item }}"
      with_items: "{{ app_containers }}"
    - name: Run nginx
      include_role: 
        name: setup-nginx
