---
# tasks file for setup-docker
- name: Add epel repository
  yum:
    name: epel-release
    state: present
- name: Add Docker-CE reository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python2-pip
- name: Install Docker-CE
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - Enable Docker
- name: Install Python SDK for Docker
  pip:
    name: docker
- name: Start Docker
  systemd:
    name: docker
    state: started
- name: Create custom network in Docker
  docker_network:
    name: exam
    ipam_config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.1
